// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechReeds.DataAccess.Data;

#nullable disable

namespace TechReeds.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechReeds.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Algorithms"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Clean Code"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Competitive Programming"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Databases"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Design Patterns"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Functional Programming"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Object-Oriented Programming"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Refactoring"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Unit Testing"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Android"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Assembly"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Name = "C Language"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Name = "C# and .NET"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Name = "C++"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            Name = "Dart"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 21,
                            Name = "Go"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 22,
                            Name = "HTML & CSS"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 23,
                            Name = "iOS"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 24,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 25,
                            Name = "JavaScript & jQuery"
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 26,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 27,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 28,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 29,
                            Name = "React"
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 30,
                            Name = "React Native"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 31,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 32,
                            Name = "Scala"
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 33,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 34,
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 35,
                            Name = "Xamarin"
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 36,
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 37,
                            Name = "Big Data"
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 38,
                            Name = "Computer Vision"
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 39,
                            Name = "Data Analysis"
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 40,
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 41,
                            Name = "Data Visualization"
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 42,
                            Name = "Deep Learning"
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 43,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 44,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 45,
                            Name = "NLP"
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 46,
                            Name = "Power BI"
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 47,
                            Name = "R Programming"
                        },
                        new
                        {
                            Id = 48,
                            DisplayOrder = 48,
                            Name = "Statistics"
                        },
                        new
                        {
                            Id = 49,
                            DisplayOrder = 49,
                            Name = "Arduino"
                        },
                        new
                        {
                            Id = 50,
                            DisplayOrder = 50,
                            Name = "ARM"
                        },
                        new
                        {
                            Id = 51,
                            DisplayOrder = 51,
                            Name = "Embedded Linux"
                        },
                        new
                        {
                            Id = 52,
                            DisplayOrder = 52,
                            Name = "Embedded Systems"
                        },
                        new
                        {
                            Id = 53,
                            DisplayOrder = 53,
                            Name = "PIC Microcontrollers"
                        },
                        new
                        {
                            Id = 54,
                            DisplayOrder = 54,
                            Name = "Raspberry Pi"
                        },
                        new
                        {
                            Id = 55,
                            DisplayOrder = 55,
                            Name = "Cybersecurity"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
